import type { FC } from "react";
import {
    AffirmIcon,
    AfterpayIcon,
    AlipayIcon,
    AmazonIcon,
    AmexIcon,
    ApplePayIcon,
    AydenIcon,
    BancontactIcon,
    BinancePayIcon,
    BitcoinCashIcon,
    BitcoinIcon,
    BitpayIcon,
    BraintreeIcon,
    CashAppPayIcon,
    CitadeleIcon,
    CoinbaseIcon,
    DinersClubIcon,
    DiscoverIcon,
    EloIcon,
    EtheriumIcon,
    ForbrugsforeningenIcon,
    GiropayIcon,
    GooglePayIcon,
    IdealIcon,
    InteracIcon,
    JCBIcon,
    KlarnaIcon,
    LightcoinIcon,
    MaestroIcon,
    MastercardIcon,
    PayPalIcon,
    PayoneerIcon,
    PaysafeIcon,
    QiwiIcon,
    RazorpayIcon,
    RevolutIcon,
    RuPayIcon,
    SEPAIcon,
    SamsungPayIcon,
    ShopPayIcon,
    ShopeePayIcon,
    SkrillIcon,
    SofortIcon,
    StripeIcon,
    UPIIcon,
    UnionPayIcon,
    VenmoIcon,
    VerifoneIcon,
    VisaIcon,
    WeChatIcon,
    WeChatPayIcon,
    WebmoneyIcon,
    WiseIcon,
    YandexIcon,
    ZelleIcon,
    ZipPayIcon,
} from "@/components/foundations/payment-icons";

const icons = [
    { name: "Visa", icon: VisaIcon },
    { name: "Mastercard", icon: MastercardIcon },
    { name: "AMEX", icon: AmexIcon },
    { name: "Discover", icon: DiscoverIcon },
    { name: "PayPal", icon: PayPalIcon },
    { name: "Apple Pay", icon: ApplePayIcon },
    { name: "Google Pay", icon: GooglePayIcon },
    { name: "Samsung Pay", icon: SamsungPayIcon },
    { name: "Stripe", icon: StripeIcon },
    { name: "Union Pay", icon: UnionPayIcon },
    { name: "Maestro", icon: MaestroIcon },
    { name: "JCB", icon: JCBIcon },
    { name: "Diners Club", icon: DinersClubIcon },
    { name: "Elo", icon: EloIcon },
    { name: "RuPay", icon: RuPayIcon },
    { name: "Affirm", icon: AffirmIcon },
    { name: "Afterpay", icon: AfterpayIcon },
    { name: "Klarna", icon: KlarnaIcon },
    { name: "Shop Pay", icon: ShopPayIcon },
    { name: "Shopee Pay", icon: ShopeePayIcon },
    { name: "Zip Pay", icon: ZipPayIcon },
    { name: "Cash App Pay", icon: CashAppPayIcon },
    { name: "Venmo", icon: VenmoIcon },
    { name: "Zelle", icon: ZelleIcon },
    { name: "Alipay", icon: AlipayIcon },
    { name: "WeChat Pay", icon: WeChatPayIcon },
    { name: "WeChat", icon: WeChatIcon },
    { name: "Amazon", icon: AmazonIcon },
    { name: "Razorpay", icon: RazorpayIcon },
    { name: "Ayden", icon: AydenIcon },
    { name: "Braintree", icon: BraintreeIcon },
    { name: "Verifone", icon: VerifoneIcon },
    { name: "Payoneer", icon: PayoneerIcon },
    { name: "Paysafe", icon: PaysafeIcon },
    { name: "Revolut", icon: RevolutIcon },
    { name: "Wise", icon: WiseIcon },
    { name: "Skrill", icon: SkrillIcon },
    { name: "Webmoney", icon: WebmoneyIcon },
    { name: "Qiwi", icon: QiwiIcon },
    { name: "Bitcoin", icon: BitcoinIcon },
    { name: "Bitcoin Cash", icon: BitcoinCashIcon },
    { name: "Etherium", icon: EtheriumIcon },
    { name: "Lightcoin", icon: LightcoinIcon },
    { name: "Binance Pay", icon: BinancePayIcon },
    { name: "Coinbase", icon: CoinbaseIcon },
    { name: "Bitpay", icon: BitpayIcon },
    { name: "UPI", icon: UPIIcon },
    { name: "SEPA", icon: SEPAIcon },
    { name: "Ideal", icon: IdealIcon },
    { name: "Bancontact", icon: BancontactIcon },
    { name: "Giropay", icon: GiropayIcon },
    { name: "Sofort", icon: SofortIcon },
    { name: "Citadele", icon: CitadeleIcon },
    { name: "Interac", icon: InteracIcon },
    { name: "Yandex", icon: YandexIcon },
    { name: "Forbrugsforeningen", icon: ForbrugsforeningenIcon },
];

export default {
    title: "Foundations/Payment Icons",
    decorators: [
        (Story: FC) => (
            <div className="flex min-h-screen w-full overflow-auto bg-primary p-8">
                <Story />
            </div>
        ),
    ],
};

export const PaymentIcons = () => (
    <div className="flex flex-wrap gap-6">
        {icons.map(({ name, icon: Icon }) => (
            <div key={name} className="flex w-28 flex-col items-center gap-2">
                <Icon className="h-8 w-11.5" />
                <span className="text-center text-xs text-tertiary">{name}</span>
            </div>
        ))}
    </div>
);
